name: flutterbaseapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cached_network_svg_image: ^1.0.0
  connectivity_widget: ^3.0.0
  dio: ^5.4.3+1
  feedback: ^3.1.0
  firebase_crashlytics: ^3.5.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  get_storage: ^2.1.1
  go_router: ^14.1.3
  image_picker: ^1.1.1
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.1
  onesignal_flutter: ^5.2.0
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^5.0.2
  responsive_sizer: ^3.3.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_flavorizr: ^2.2.3
  pub_version_plus: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_generate/appicon.jpg"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon_generate/appicon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon_generate/appicon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon_generate/appicon.jpg"
  
flavorizr:
  flavors:
    dev: #used while development
      app:
        name: "flutterbaseapp Dev"
      android:
        applicationId: "com.example.flutterbaseapp.dev"
      ios:
        bundleId: "com.example.flutterbaseapp.dev"
      macos:
        bundleId: "com.example.flutterbaseapp.dev"

    stg: #used for giving app for testing
      app:
        name: "flutterbaseapp Test"
      android:
        applicationId: "com.example.flutterbaseapp.stg"
      ios:
        bundleId: "com.example.flutterbaseapp.stg"
      macos:
        bundleId: "com.example.flutterbaseapp.stg"

    prod: #use this app to upload to production
      app:
        name: "flutterbaseapp"
      android:
        applicationId: "com.example.flutterbaseapp.prod"
      ios:
        bundleId: "com.example.flutterbaseapp.prod"
      macos:
        bundleId: "com.example.flutterbaseapp.prod"

      

    


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
