name: flutterbaseapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cached_network_svg_image: ^1.0.0
  connectivity_widget: ^3.0.0
  dio: ^5.4.3+1
  feedback: ^3.1.0
  firebase_core: ^2.31.1
  firebase_crashlytics: ^3.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  get_storage: ^2.1.1
  go_router: ^13.2.5
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.1
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.1
  onesignal_flutter: ^5.2.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  responsive_sizer: ^3.3.1
  upgrader: ^10.3.0
  url_launcher: ^6.2.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7
  flutter_flavorizr: ^2.2.3
  pub_version_plus: ^1.1.0
  
flavorizr: # to run : flutter pub run flutter_flavorizr
  flavors: 
    dev: #used while development
        app:
          name: "flutterbaseapp Dev"
        android:
          applicationId: "com.example.flutterbaseapp.dev"
          firebase:
            config: "firebase/dev/google-services.json"
        ios:
          bundleId: "com.example.flutterbaseapp.dev"
          firebase:
            config: "firebase/dev/GoogleService-Info.plist"
        macos:
          bundleId: "com.example.flutterbaseapp.dev"
          firebase:
            config: "firebase/dev/GoogleService-Info.plist"

    stg: #used for giving app for testing
        app:
          name: "flutterbaseapp Test"
        android:
          applicationId: "com.example.flutterbaseapp.stg"
          firebase:
            config: "firebase/stg/google-services.json"
        ios:
          bundleId: "com.example.flutterbaseapp.stg"
          firebase:
            config: "firebase/stg/GoogleService-Info.plist"
        macos:
          bundleId: "com.example.flutterbaseapp.stg"
          firebase:
            config: "firebase/stg/GoogleService-Info.plist"

    prod: #use this app to upload to production
        app:
          name: "flutterbaseapp"
        android:
          applicationId: "com.example.flutterbaseapp.prod"
          firebase:
            config: "firebase/prod/google-services.json"
        ios:
          bundleId: "com.example.flutterbaseapp.prod"
          firebase:
            config: "firebase/prod/GoogleService-Info.plist"
        macos:
          bundleId: "com.example.flutterbaseapp.prod"
          firebase:
            config: "firebase/prod/GoogleService-Info.plist"


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - .env
    - .env.dev
    - .env.stg
    - .env.prod
    - asset/other/
    - asset/app_icon_generate/
    - asset/svg/
    - asset/nav/
    - asset/icon/
    - asset/img/
    - asset/temp/
